[package]
name = "QUITBADHABITui"
version = "0.1.0"
authors = ["AIT EL HAJ Abdelouadoud <abdelouadoud.aitelhaj.mailme@example.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
